import type { Metadata } from "next";
import { Poppins, Geist } from "next/font/google";
import "./globals.css";
import { auth } from "@/lib/auth/server";
import { NeonAuthUIProvider } from "@neondatabase/auth/react";
import { authClient } from "@/lib/auth/client";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, 
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.className} h-full antialiased`} suppressHydrationWarning
    >
      
      <body>
      <NeonAuthUIProvider authClient={authClient as any} social={{ providers: ['google'] }}>
      <main>
      {children}
       <ToastContainer
          position="top-right"
          autoClose={3000}
        />
      </main>
      </NeonAuthUIProvider>
      </body>
    </html>
  );
}
