import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { NeonAuthUIProvider } from "@neondatabase/auth/react";
import { authClient } from "@/lib/auth/client";
import { ThemeProvider } from "next-themes";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, 
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.className} h-full antialiased`} suppressHydrationWarning
    >
      
      <body>
      <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false} disableTransitionOnChange>
        <NeonAuthUIProvider authClient={authClient} social={{ providers: ['google'] }}>
          <main>
            {children}
            <ToastContainer position="top-right" autoClose={3000} />
          </main>
        </NeonAuthUIProvider>
      </ThemeProvider>
      </body>
    </html>
  );
}
